CREATE TABLE products (
    upc           VARCHAR(14)  PRIMARY KEY,
    name          TEXT         NOT NULL,
    image_url     TEXT,
    first_seen_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE price_checks (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upc        VARCHAR(14)  NOT NULL REFERENCES products (upc) ON DELETE CASCADE,
    checked_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_price_checks_upc_checked_at ON price_checks (upc, checked_at DESC);

CREATE TABLE price_snapshots (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_check_id BIGINT         NOT NULL REFERENCES price_checks (id) ON DELETE CASCADE,
    store          VARCHAR(100)   NOT NULL,
    price          NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    title          TEXT,
    link           TEXT,
    thumbnail_url  TEXT,
    UNIQUE (price_check_id, store)
);

CREATE TABLE scans (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upc        VARCHAR(14)  NOT NULL REFERENCES products (upc) ON DELETE CASCADE,
    device_id  VARCHAR(64),
    scanned_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_scans_device_id_scanned_at ON scans (device_id, scanned_at DESC);
